### ISSUE TITLE
Комментарии к первоначальной заявке [прислана после дедлайна]

### ISSUE THREAD

**Issue by aakuptsov** [opaloxx/match3#1]
1. Файл с заявкой необходимо переименовать в соответствии с требованиями.

2. В проблемном поле описана не проблема, а то, что будет делать продукт. Это не одно и то же. Проблема - это некое несоответствие в реальном мире ожиданиям, она описывается в словах, фиксирующих недостаток чего-либо, отсутствие чего-либо, не достаточно быстрый / удобный / бесплатный функционал и т. п. 

3. Люди любого возраста - это непродуктивный подход к описанию целевой аудитории. Даже общий интерес к головоломкам имеет некую возрастную вариацию, от одной возрастной группы к другой. Необходимо выделить 2-3 возрастные группы. Желательно также указать и другие признаки ц/а-групп. 

4. В аппаратных требованиях в случае браузера надо написать один-два конкретных браузера и минимальную версию каждого, на которой это будет работать продукт. 

5. Функциональных требований должно быть 7 (у тебя есть), но  в них должны быть описаны возможности, которые предоставляются пользователю. Например, рейтинг: возможность подсчёта очков и ведение рейтинга. 

6. В разделе аналогичных продуктов необходимо не просто их перечислить, а проанализировать: указать, какие аспекты проблемы из проблемного поля они не решают. 

7. В целом хочется отметить, что реализация одной головоломки на первый взгляд делает проект достаточно простым. Здесь нужна, скорее, серия головоломок, объединённая какой-то, возможно, сюжетной линией.

**Comment by dpaleyev** [comment]
1. Как я понял, основное отличие от множества других игр "три в ряд" это наличие мультиплеера. Однако не проанализированы примеры игры "три в ряд", где он есть: "Puzzle Quest: Challenge of the Warlords", "Match Masters ‎- PvP Match 3". И собственно это основная проблема, так как при существовании хороших (возможно они плохие) мультиплеерных игр такого жанра проблемное поле становится не валидным. 
2. Функциональные требование написаны очень подробно, молодец! Однако функциональные требования должны представлять из себя !функции!, которые предлагает твоё приложение пользователю. Пример: игровое поле - это не функция, оно просто есть; "Уровень сложности" -> "Выбор уровня сложности" и тд.

**Comment by dpaleyev** [comment]
Просим в будущем не закрывать Issues до окончания ИВР
